spring:
  datasource:
    username: finley
    password: password
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/gift_shop
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
  application:
    name: catalog-service

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

comments-service:
  comment-minimum-length: 3