services:
  api_service:
    build: .
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysqldb
    networks:
      - spring
    ports:
      - 8080:8080

  mysqldb:
    image: "mysql/mysql-server:5.7"
    restart: unless-stopped
    ports:
      - 3306:3306
    networks:
      - spring
    environment:
      MYSQL_DATABASE: gift_shop
      MYSQL_USER: finley
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

networks:
  spring:
    driver: bridge