version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql_db
    links:
      - mysql_db:app_db
  mysql_db:
    image: "mysql/mysql-server:8.0.27"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: gift_shop
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password