version: "3.8"
services:
  mysqldb:
    image: mysql:8.0.28
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=gift_shop
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: ./notification-service
    restart: on-failure
    env_file: ./.env
    ports:
      - 8081:8081
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/gift_shop?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "password",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
volumes:
  db: